### ISSUE TITLE
Gas Mask will not open

### ISSUE THREAD

**Issue by nero332** [2ndalpha/gasmask#96]
When upgrading to the latest version of OS X (10.11.5), Gas Mask will no longer open.

Steps to repro:
1. Upgrade to the latest version of OS X
2. Attempt to open Gas Mask
3. Gas Mask will not open

We are seeing this issue on multiple machines, where post-upgrade the app will not open. 

We love the app, but with this issue was are forced to transition to another app.

**Comment by 2ndalpha** [comment]
Please make sure you are not running in menu-bar-only mode. Is there Gas Mask icon in the right top corner of the screen?

**Comment by quakeboy** [comment]
Wow, I had no idea. I even restarted the machine.
I thought the app didn't work.

It was because every time I launched it opened a window. And now I have no idea how it automatically switched to menu-bar-only mode. But thanks for this answer.

It might be nice to notify that when we click the red close button on the editor window, it automatically goes to menu-bar-only mode.

**Comment by quakeboy** [comment]
I even opened the mac "console" app to check for error logs. Saying this, as many people will not know that the app is running on the menu bar.

**Comment by code-for-coffee** [comment]
Chiming in - this was my problem but I had no idea that it was in the menu bar.

**Comment by its-ovrcode** [comment]
No even in the menubar!
